### ISSUE TITLE
Not Building

### ISSUE THREAD

**Issue by ardan-bkennedy** [fogfish/word2vec#1] opened 2024-07-01 16:19 UTC
Hi. I was excited to find the project. You have multiple module files and you are using the module as a dependency. I was wondering if you could help me?

**Comment by fogfish** [comment] 2024-07-02 08:26
Thank you for raising the issue. It would be helpful if you can describe the issue and share log of build failed. It would help me to improve the installation instructions.

In the nutshell:
1. You need to build the [word2vec C++ library](https://github.com/fogfish/word2vec?tab=readme-ov-file#building-the-c-library). It requires C++ toolchain on your machine, usage of brew is the faster fail to install it.
2. You need to [build the frontend](https://github.com/fogfish/word2vec?tab=readme-ov-file#training-the-model) for model training. It requires Golang toolchain https://go.dev
3. Usage of the library requires only "import".

**Comment by ardan-bkennedy** [comment] 2024-07-02 10:47
Thanks for responding. You are 100% right, I needed to give you that information. Sorry!

I spent a few hours fighting CGO settings so the compiler could find the header and the dynamic library. I'm building some training material and wanted to play with word2vec.

Your go install command did not work out of the box even when everything was setup. The Mac needs certain env variables setup properly to find things. It's always a nightmare.

Also, it's best to just keep 1 set of module files at the root of the module. Having multiple always creates other problems.

in the end, I brought your code into this project and changed the CGO settings so someone can just clone and run the example.

https://github.com/ardanlabs/vector

Yes I am leaving a built version of the dynamic library in the repo, but I will let people know they can rebuild that themselves if they don't trust it. In the makefile for example 3 you will see how I pass the env var needed for things to build and run.

I also cleaned up the code a bit and added proper comments.

While I have you. I'm not a CGO guru by any means. Does this library have support for comparing two words and telling you how similar they are? I search the cpp code and couldn't find that. I wrote my own using a cosine similarity algorithm, but it would have been nice to use the same algorithm the cpp library is using for the nearest call.

**Comment by fogfish** [comment] 2024-07-02 14:47
Thank for providing more context!

I believe the command `go install github.com/fogfish/word2vec/w2v@latest` has failed with an error:

```bash
# github.com/fogfish/word2vec/trainer
devel/go/pkg/mod/github.com/fogfish/word2vec/trainer@v0.0.0-20240222201857-2ad2b3dd3ae0/trainer.go:15:10: fatal error: 'w2v.h' file not found
#include "w2v.h"
         ^~~~~~~
1 error generated.
```

The issue is caused by outdated dependencies within `github.com/fogfish/word2vec/w2v` module. Thank you for reporting this bug. It is fixed now.

```bash
go install github.com/fogfish/word2vec/w2v@v0.0.0-20240702140847-ffa755fd33f9
```

---

> Your go install command did not work out of the box even when everything was setup. The Mac needs certain env variables setup properly to find things. It's always a nightmare.

I believe this is due to the bug mentioned above. Typically, CGO works out of the box if you do Golang installation from https://go.dev/dl/ . You can share the output of `go env`. You have to watch out the following variables:

```
CGO_ENABLED='1'

GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/98/0ttsxqrn6q13jwh9shqc30jr0000gn/T/go-build1612648755=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

> Also, it's best to just keep 1 set of module files at the root of the module. Having multiple always creates other problems.

Having multiple modules in one repo is [legitimate solution](https://go.dev/doc/modules/managing-source). It simplify mono-repo development (e.g. https://github.com/aws/aws-sdk-go-v2). In case of this library,  multiple modules are used to isolate dependencies. The frontend utility `w2v` uses `github.com/spf13/cobra`, `github.com/spf13/viper` and few others which should not be injected into the code of library users.

> I am leaving a built version of the dynamic library in the repo... 

Yes, this is a solution but I'd rather consider to automate the process with GitHub Actions or brew tap. Feel free to contribute.

> I also cleaned up the code a bit and added proper comments.

It would be nice to have contribution back on this.


 > Does this library have support for comparing two words and telling you how similar they are?

It does not make sense due to CGO overhead. It has to be either inline assembly code or pure native Golang with unrolled loop technique. In the past, I've conducted performance analysis "Nanosecond Optimization for float32 math in Golang". The result of my study is reflected in https://github.com/kshard/vector.  For example, Native C & CGO takes about 492.5 ns/op for dot product while inline SIMD assembly 340.4 ns/op. If you are interesting to hear more about it, I am happy to share my experience.

**Comment by ardan-bkennedy** [comment] 2024-07-02 15:06
> The issue is caused by outdated dependencies within github.com/fogfish/word2vec/w2v module. Thank you for reporting this bug. It is fixed now.

I'm happy you fixed this!!

> Having multiple modules in one repo is [legitimate solution](https://go.dev/doc/modules/managing-source).

It adds a lot of complexity and I haven't seen the need for it. That being said, if it's working for you then it's all good.

> It does not make sense due to CGO overhead. It has to be either inline assembly code or pure native Golang with unrolled loop technique.

I wanted it only so I was using the same algorithm as the Lookup call. I am going to check out the package you referenced. Thanks for sharing that.

> It would be nice to have contribution back on this.

I would look at the code and see if you even want it.

https://github.com/ardanlabs/vector/tree/main/foundation/word2vec

**Closed** 2024-07-02 15:21 UTC
